% This is the driver layer of the TRM model but for sWBGT. Similar to the TRM model for T2, it includes 3 main components: 
% 1, the TRM attribution itself (see Rigden and Li, 2017, Liao et al. 2018, Li et al. 2019, Wang et al. 2019), 
% 2, the optimization of m described in Liao et al. (2018 JGR-biogeosciences), 
% 3, the final calculation with the optimized m.  
%
% Currently the code is set up to read in inputs as two-dimensional arrays 
% in space (row) and time (column). 
%
% At a given space (i.e., for a given row), the m_optimize routine currently 
% uses all data in the time domain and at the temporal resolution provided 
% by the inputs to optimize m. This could be changed. 

function [Diff_T2,Diff_q2,Diff_WGT,mask,m_TRM_sel_opt_T2,m_TRM_sel_opt_q2,m_TRM_sel_opt_WGT_2m,...
          Rn_str_ref, Grnd_ref,ro_ref,ra_ref,rs_ref,f_TRM_ref,...
          Rn_str_sel, Grnd_sel,ro_sel,ra_sel,rs_sel,f_TRM_sel,...
          ra_prime_ref,f_2_TRM_ref,...
          ra_prime_sel,f_2_TRM_sel,...            
          dT2_dswd_TRM_ref,dT2_drld_TRM_ref,dT2_dTa_TRM_ref,dT2_dqa_TRM_ref,dT2_dalpha_TRM_ref,dT2_demis_TRM_ref,dT2_dra_TRM_ref,dT2_drs_TRM_ref,dT2_dGrnd_TRM_ref,dT2_dra_prime_TRM_ref,...
          dT2_dswd_TRM_sel,dT2_drld_TRM_sel,dT2_dTa_TRM_sel,dT2_dqa_TRM_sel,dT2_dalpha_TRM_sel,dT2_demis_TRM_sel,dT2_dra_TRM_sel,dT2_drs_TRM_sel,dT2_dGrnd_TRM_sel,dT2_dra_prime_TRM_sel,...
          dq2_dswd_TRM_ref,dq2_drld_TRM_ref,dq2_dTa_TRM_ref,dq2_dqa_TRM_ref,dq2_dalpha_TRM_ref,dq2_demis_TRM_ref,dq2_dra_TRM_ref,dq2_drs_TRM_ref,dq2_dGrnd_TRM_ref,dq2_dra_prime_TRM_ref,...
          dq2_dswd_TRM_sel,dq2_drld_TRM_sel,dq2_dTa_TRM_sel,dq2_dqa_TRM_sel,dq2_dalpha_TRM_sel,dq2_demis_TRM_sel,dq2_dra_TRM_sel,dq2_drs_TRM_sel,dq2_dGrnd_TRM_sel,dq2_dra_prime_TRM_sel,...
          dWGT_dswd_TRM_ref,dWGT_drld_TRM_ref,dWGT_dTa_TRM_ref,dWGT_dqa_TRM_ref,dWGT_dalpha_TRM_ref,dWGT_demis_TRM_ref,dWGT_dra_TRM_ref,dWGT_drs_TRM_ref,dWGT_dGrnd_TRM_ref,dWGT_dra_prime_TRM_ref,...
          dWGT_dswd_TRM_sel,dWGT_drld_TRM_sel,dWGT_dTa_TRM_sel,dWGT_dqa_TRM_sel,dWGT_dalpha_TRM_sel,dWGT_demis_TRM_sel,dWGT_dra_TRM_sel,dWGT_drs_TRM_sel,dWGT_dGrnd_TRM_sel,dWGT_dra_prime_TRM_sel,...
          dT2_dswd_TRM,dT2_drld_TRM,dT2_dTa_TRM,dT2_dqa_TRM,dT2_dalpha_TRM,dT2_demis_TRM,dT2_dra_TRM,dT2_drs_TRM,dT2_dGrnd_TRM,dT2_dra_prime_TRM,...
          T2_term_swd_TRM,T2_term_rld_TRM,T2_term_Ta_TRM,T2_term_qa_TRM,T2_term_alpha_TRM,T2_term_emis_TRM,T2_term_ra_TRM,T2_term_rs_TRM,T2_term_Grnd_TRM,T2_term_ra_prime_TRM,...
          T2_sum_TRM,...
          dq2_dswd_TRM,dq2_drld_TRM,dq2_dTa_TRM,dq2_dqa_TRM,dq2_dalpha_TRM,dq2_demis_TRM,dq2_dra_TRM,dq2_drs_TRM,dq2_dGrnd_TRM,dq2_dra_prime_TRM,...
          q2_term_swd_TRM,q2_term_rld_TRM,q2_term_Ta_TRM,q2_term_qa_TRM,q2_term_alpha_TRM,q2_term_emis_TRM,q2_term_ra_TRM,q2_term_rs_TRM,q2_term_Grnd_TRM,q2_term_ra_prime_TRM,...
          q2_sum_TRM,...          
          dWGT_dswd_TRM,dWGT_drld_TRM,dWGT_dTa_TRM,dWGT_dqa_TRM,dWGT_dalpha_TRM,dWGT_demis_TRM,dWGT_dra_TRM,dWGT_drs_TRM,dWGT_dGrnd_TRM,dWGT_dra_prime_TRM,...
          WGT_term_swd_TRM,WGT_term_rld_TRM,WGT_term_Ta_TRM,WGT_term_qa_TRM,WGT_term_alpha_TRM,WGT_term_emis_TRM,WGT_term_ra_TRM,WGT_term_rs_TRM,WGT_term_Grnd_TRM,WGT_term_ra_prime_TRM,...
          WGT_sum_TRM] = REF_HI_TRM_driver(...
              rho_air,... % air density (kg/m3)
              Cp,...      % heat capacity of dry air (J/kg/K)
              sb,...      % stephan-boltzman constant (W/(m^2 K^4))
              lv,...      % latent heat of vaporization (J/kg)
              limit,...   % the limit of sensible and latent heat fluxes for creating masks
              do_optimize,...  % do optimization for m or not
              use_previously_optimized_m,... % have you already done optimization for m or not
              data_path,...
              Psurf_ref,swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,Qh_ref,Qle_ref,Ts_ref,T2_ref,q2_ref,...  % inputs over the reference patch
              Psurf_sel,swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,Qh_sel,Qle_sel,Ts_sel,T2_sel,q2_sel)     % inputs over the perturbed patch


%% TRM calculations

[Diff_WGT,Diff_T2,Diff_q2,...  
          Rn_str_ref, Grnd_ref,ro_ref,ra_ref,rs_ref,f_TRM_ref,...
          Rn_str_sel, Grnd_sel,ro_sel,ra_sel,rs_sel,f_TRM_sel,...    
          ra_prime_ref,f_2_TRM_ref,...
          ra_prime_sel,f_2_TRM_sel,...            
          dT2_dswd_TRM_ref,dT2_drld_TRM_ref,dT2_dTa_TRM_ref,dT2_dqa_TRM_ref,dT2_dalpha_TRM_ref,dT2_demis_TRM_ref,dT2_dra_TRM_ref,dT2_drs_TRM_ref,dT2_dGrnd_TRM_ref,dT2_dra_prime_TRM_ref,...
          dT2_dswd_TRM_sel,dT2_drld_TRM_sel,dT2_dTa_TRM_sel,dT2_dqa_TRM_sel,dT2_dalpha_TRM_sel,dT2_demis_TRM_sel,dT2_dra_TRM_sel,dT2_drs_TRM_sel,dT2_dGrnd_TRM_sel,dT2_dra_prime_TRM_sel,...
          dq2_dswd_TRM_ref,dq2_drld_TRM_ref,dq2_dTa_TRM_ref,dq2_dqa_TRM_ref,dq2_dalpha_TRM_ref,dq2_demis_TRM_ref,dq2_dra_TRM_ref,dq2_drs_TRM_ref,dq2_dGrnd_TRM_ref,dq2_dra_prime_TRM_ref,...
          dq2_dswd_TRM_sel,dq2_drld_TRM_sel,dq2_dTa_TRM_sel,dq2_dqa_TRM_sel,dq2_dalpha_TRM_sel,dq2_demis_TRM_sel,dq2_dra_TRM_sel,dq2_drs_TRM_sel,dq2_dGrnd_TRM_sel,dq2_dra_prime_TRM_sel,...
          dWGT_dswd_TRM_ref,dWGT_drld_TRM_ref,dWGT_dTa_TRM_ref,dWGT_dqa_TRM_ref,dWGT_dalpha_TRM_ref,dWGT_demis_TRM_ref,dWGT_dra_TRM_ref,dWGT_drs_TRM_ref,dWGT_dGrnd_TRM_ref,dWGT_dra_prime_TRM_ref,...
          dWGT_dswd_TRM_sel,dWGT_drld_TRM_sel,dWGT_dTa_TRM_sel,dWGT_dqa_TRM_sel,dWGT_dalpha_TRM_sel,dWGT_demis_TRM_sel,dWGT_dra_TRM_sel,dWGT_drs_TRM_sel,dWGT_dGrnd_TRM_sel,dWGT_dra_prime_TRM_sel]=...          
          REF_HI_TRM(rho_air,Cp,sb,lv,...
              Psurf_ref,swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,Qh_ref,Qle_ref,Ts_ref,T2_ref,q2_ref,...
              Psurf_sel,swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,Qh_sel,Qle_sel,Ts_sel,T2_sel,q2_sel); 
          
          
%% criteria of selecting data

mask = create_mask_T2(ra_ref,ra_sel,ra_prime_ref,ra_prime_sel,rs_ref,rs_sel,Qh_ref,Qh_sel,Qle_ref,Qle_sel,limit);


%% optimize m

if (use_previously_optimized_m == 1)
  
    if isfile([data_path 'm_TRM_sel_opt_WGT_2m.mat'])
        load([data_path 'm_TRM_sel_opt_WGT_2m.mat'])
    else
        disp(['no m_TRM_sel_opt_WGT_2m.mat exits, please change use_previously_optimized_m to 0'])
    end
 
else
    
if (do_optimize == 1)

m_TRM_sel_opt_q2=m_optimize_T2(Diff_q2,mask,...
                     dq2_dswd_TRM_ref,dq2_drld_TRM_ref,dq2_dTa_TRM_ref,dq2_dqa_TRM_ref,dq2_dalpha_TRM_ref,dq2_demis_TRM_ref,dq2_dra_TRM_ref,dq2_drs_TRM_ref,dq2_dGrnd_TRM_ref,dq2_dra_prime_TRM_ref,...
                     dq2_dswd_TRM_sel,dq2_drld_TRM_sel,dq2_dTa_TRM_sel,dq2_dqa_TRM_sel,dq2_dalpha_TRM_sel,dq2_demis_TRM_sel,dq2_dra_TRM_sel,dq2_drs_TRM_sel,dq2_dGrnd_TRM_sel,dq2_dra_prime_TRM_sel,...
                     swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,ra_ref,rs_ref,Grnd_ref,ra_prime_ref,...
                     swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,ra_sel,rs_sel,Grnd_sel,ra_prime_sel);

                 
m_TRM_sel_opt_T2=m_optimize_T2(Diff_T2,mask,...
                     dT2_dswd_TRM_ref,dT2_drld_TRM_ref,dT2_dTa_TRM_ref,dT2_dqa_TRM_ref,dT2_dalpha_TRM_ref,dT2_demis_TRM_ref,dT2_dra_TRM_ref,dT2_drs_TRM_ref,dT2_dGrnd_TRM_ref,dT2_dra_prime_TRM_ref, ...
                     dT2_dswd_TRM_sel,dT2_drld_TRM_sel,dT2_dTa_TRM_sel,dT2_dqa_TRM_sel,dT2_dalpha_TRM_sel,dT2_demis_TRM_sel,dT2_dra_TRM_sel,dT2_drs_TRM_sel,dT2_dGrnd_TRM_sel,dT2_dra_prime_TRM_sel, ...
                     swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,ra_ref,rs_ref,Grnd_ref,ra_prime_ref,...
                     swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,ra_sel,rs_sel,Grnd_sel,ra_prime_sel);


m_TRM_sel_opt_WGT_2m=m_optimize_T2(Diff_WGT,mask,...
                     dWGT_dswd_TRM_ref,dWGT_drld_TRM_ref,dWGT_dTa_TRM_ref,dWGT_dqa_TRM_ref,dWGT_dalpha_TRM_ref,dWGT_demis_TRM_ref,dWGT_dra_TRM_ref,dWGT_drs_TRM_ref,dWGT_dGrnd_TRM_ref,dWGT_dra_prime_TRM_ref,...
                     dWGT_dswd_TRM_sel,dWGT_drld_TRM_sel,dWGT_dTa_TRM_sel,dWGT_dqa_TRM_sel,dWGT_dalpha_TRM_sel,dWGT_demis_TRM_sel,dWGT_dra_TRM_sel,dWGT_drs_TRM_sel,dWGT_dGrnd_TRM_sel,dWGT_dra_prime_TRM_sel,...
                     swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,ra_ref,rs_ref,Grnd_ref,ra_prime_ref,...
                     swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,ra_sel,rs_sel,Grnd_sel,ra_prime_sel);

                 
save ([data_path 'm_TRM_sel_opt_WGT_2m'], 'm_TRM_sel_opt_T2','m_TRM_sel_opt_q2','m_TRM_sel_opt_WGT_2m')

else if (do_optimize == 0)
        
m_TRM_sel_opt_T2= zeros(length(Diff_T2(:,1)),1) + 1;
m_TRM_sel_opt_q2= zeros(length(Diff_q2(:,1)),1) + 1;
m_TRM_sel_opt_WGT_2m= zeros(length(Diff_WGT(:,1)),1) + 1;

save ([data_path 'm_TRM_sel_opt_WGT_2m'], 'm_TRM_sel_opt_T2','m_TRM_sel_opt_q2','m_TRM_sel_opt_WGT_2m')

    end
    
end

end

%% calculate the weighted average of partial derivatives

[dT2_dswd_TRM,dT2_drld_TRM,dT2_dTa_TRM,dT2_dqa_TRM,dT2_dalpha_TRM,dT2_demis_TRM,dT2_dra_TRM,dT2_drs_TRM,dT2_dGrnd_TRM,dT2_dra_prime_TRM,...
 T2_term_swd_TRM,T2_term_rld_TRM,T2_term_Ta_TRM,T2_term_qa_TRM,T2_term_alpha_TRM,T2_term_emis_TRM,T2_term_ra_TRM,T2_term_rs_TRM,T2_term_Grnd_TRM,T2_term_ra_prime_TRM,...
 T2_sum_TRM] = final_calculation_T2(m_TRM_sel_opt_T2,mask,...
                     dT2_dswd_TRM_ref,dT2_drld_TRM_ref,dT2_dTa_TRM_ref,dT2_dqa_TRM_ref,dT2_dalpha_TRM_ref,dT2_demis_TRM_ref,dT2_dra_TRM_ref,dT2_drs_TRM_ref,dT2_dGrnd_TRM_ref,dT2_dra_prime_TRM_ref,...
                     dT2_dswd_TRM_sel,dT2_drld_TRM_sel,dT2_dTa_TRM_sel,dT2_dqa_TRM_sel,dT2_dalpha_TRM_sel,dT2_demis_TRM_sel,dT2_dra_TRM_sel,dT2_drs_TRM_sel,dT2_dGrnd_TRM_sel,dT2_dra_prime_TRM_sel,...
                     swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,ra_ref,rs_ref,Grnd_ref,ra_prime_ref,...
                     swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,ra_sel,rs_sel,Grnd_sel,ra_prime_sel);                 
                
[dq2_dswd_TRM,dq2_drld_TRM,dq2_dTa_TRM,dq2_dqa_TRM,dq2_dalpha_TRM,dq2_demis_TRM,dq2_dra_TRM,dq2_drs_TRM,dq2_dGrnd_TRM,dq2_dra_prime_TRM,...
 q2_term_swd_TRM,q2_term_rld_TRM,q2_term_Ta_TRM,q2_term_qa_TRM,q2_term_alpha_TRM,q2_term_emis_TRM,q2_term_ra_TRM,q2_term_rs_TRM,q2_term_Grnd_TRM,q2_term_ra_prime_TRM,...
 q2_sum_TRM] = final_calculation_T2(m_TRM_sel_opt_q2,mask,...
                     dq2_dswd_TRM_ref,dq2_drld_TRM_ref,dq2_dTa_TRM_ref,dq2_dqa_TRM_ref,dq2_dalpha_TRM_ref,dq2_demis_TRM_ref,dq2_dra_TRM_ref,dq2_drs_TRM_ref,dq2_dGrnd_TRM_ref,dq2_dra_prime_TRM_ref,...
                     dq2_dswd_TRM_sel,dq2_drld_TRM_sel,dq2_dTa_TRM_sel,dq2_dqa_TRM_sel,dq2_dalpha_TRM_sel,dq2_demis_TRM_sel,dq2_dra_TRM_sel,dq2_drs_TRM_sel,dq2_dGrnd_TRM_sel,dq2_dra_prime_TRM_sel,...
                     swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,ra_ref,rs_ref,Grnd_ref,ra_prime_ref,...
                     swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,ra_sel,rs_sel,Grnd_sel,ra_prime_sel);
                 
[dWGT_dswd_TRM,dWGT_drld_TRM,dWGT_dTa_TRM,dWGT_dqa_TRM,dWGT_dalpha_TRM,dWGT_demis_TRM,dWGT_dra_TRM,dWGT_drs_TRM,dWGT_dGrnd_TRM,dWGT_dra_prime_TRM,...
 WGT_term_swd_TRM,WGT_term_rld_TRM,WGT_term_Ta_TRM,WGT_term_qa_TRM,WGT_term_alpha_TRM,WGT_term_emis_TRM,WGT_term_ra_TRM,WGT_term_rs_TRM,WGT_term_Grnd_TRM,WGT_term_ra_prime_TRM,...
 WGT_sum_TRM] = final_calculation_T2(m_TRM_sel_opt_WGT_2m,mask,...
                     dWGT_dswd_TRM_ref,dWGT_drld_TRM_ref,dWGT_dTa_TRM_ref,dWGT_dqa_TRM_ref,dWGT_dalpha_TRM_ref,dWGT_demis_TRM_ref,dWGT_dra_TRM_ref,dWGT_drs_TRM_ref,dWGT_dGrnd_TRM_ref,dWGT_dra_prime_TRM_ref,...
                     dWGT_dswd_TRM_sel,dWGT_drld_TRM_sel,dWGT_dTa_TRM_sel,dWGT_dqa_TRM_sel,dWGT_dalpha_TRM_sel,dWGT_demis_TRM_sel,dWGT_dra_TRM_sel,dWGT_drs_TRM_sel,dWGT_dGrnd_TRM_sel,dWGT_dra_prime_TRM_sel,...
                     swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,ra_ref,rs_ref,Grnd_ref,ra_prime_ref,...
                     swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,ra_sel,rs_sel,Grnd_sel,ra_prime_sel);




