% This is the Two-Resistance Mechanism attribution method for sWBGT

function [Diff_WGT,Diff_T2,Diff_q2,...  
          Rn_str_ref, Grnd_ref,ro_ref,ra_ref,rs_ref,f_TRM_ref,...
          Rn_str_sel, Grnd_sel,ro_sel,ra_sel,rs_sel,f_TRM_sel,...    
          ra_prime_ref,f_2_TRM_ref,...
          ra_prime_sel,f_2_TRM_sel,...            
          dT2_dswd_TRM_ref,dT2_drld_TRM_ref,dT2_dTa_TRM_ref,dT2_dqa_TRM_ref,dT2_dalpha_TRM_ref,dT2_demis_TRM_ref,dT2_dra_TRM_ref,dT2_drs_TRM_ref,dT2_dGrnd_TRM_ref,dT2_dra_prime_TRM_ref,...
          dT2_dswd_TRM_sel,dT2_drld_TRM_sel,dT2_dTa_TRM_sel,dT2_dqa_TRM_sel,dT2_dalpha_TRM_sel,dT2_demis_TRM_sel,dT2_dra_TRM_sel,dT2_drs_TRM_sel,dT2_dGrnd_TRM_sel,dT2_dra_prime_TRM_sel,...
          dq2_dswd_TRM_ref,dq2_drld_TRM_ref,dq2_dTa_TRM_ref,dq2_dqa_TRM_ref,dq2_dalpha_TRM_ref,dq2_demis_TRM_ref,dq2_dra_TRM_ref,dq2_drs_TRM_ref,dq2_dGrnd_TRM_ref,dq2_dra_prime_TRM_ref,...
          dq2_dswd_TRM_sel,dq2_drld_TRM_sel,dq2_dTa_TRM_sel,dq2_dqa_TRM_sel,dq2_dalpha_TRM_sel,dq2_demis_TRM_sel,dq2_dra_TRM_sel,dq2_drs_TRM_sel,dq2_dGrnd_TRM_sel,dq2_dra_prime_TRM_sel,...
          dWGT_dswd_TRM_ref,dWGT_drld_TRM_ref,dWGT_dTa_TRM_ref,dWGT_dqa_TRM_ref,dWGT_dalpha_TRM_ref,dWGT_demis_TRM_ref,dWGT_dra_TRM_ref,dWGT_drs_TRM_ref,dWGT_dGrnd_TRM_ref,dWGT_dra_prime_TRM_ref,...
          dWGT_dswd_TRM_sel,dWGT_drld_TRM_sel,dWGT_dTa_TRM_sel,dWGT_dqa_TRM_sel,dWGT_dalpha_TRM_sel,dWGT_demis_TRM_sel,dWGT_dra_TRM_sel,dWGT_drs_TRM_sel,dWGT_dGrnd_TRM_sel,dWGT_dra_prime_TRM_sel]=...          
          REF_HI_TRM(rho_air,Cp,sb,lv,...
              Psurf_ref,swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,Qh_ref,Qle_ref,Ts_ref,T2_ref,q2_ref,...
              Psurf_sel,swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,Qh_sel,Qle_sel,Ts_sel,T2_sel,q2_sel)           
%% calculate surface sWBGT difference
                  
[WGT_ref, WGT_sel,...
    dWGT_dT2_ref, dWGT_dq2_ref, dWGT_dps_ref, ...
    dWGT_dT2_sel, dWGT_dq2_sel, dWGT_dps_sel] ...
    = sWBGT(Psurf_ref,T2_ref,q2_ref,Psurf_sel,T2_sel,q2_sel);

Diff_WGT = WGT_sel - WGT_ref;

          
[Diff_T2,...
          Rn_str_ref, Grnd_ref,ro_ref,ra_ref,rs_ref,f_TRM_ref,...
          Rn_str_sel, Grnd_sel,ro_sel,ra_sel,rs_sel,f_TRM_sel,... 
          ra_prime_ref,f_2_TRM_ref,...
          ra_prime_sel,f_2_TRM_sel,...            
          dT2_dswd_TRM_ref,dT2_drld_TRM_ref,dT2_dTa_TRM_ref,dT2_dqa_TRM_ref,dT2_dalpha_TRM_ref,dT2_demis_TRM_ref,dT2_dra_TRM_ref,dT2_drs_TRM_ref,dT2_dGrnd_TRM_ref,dT2_dra_prime_TRM_ref,...
          dT2_dswd_TRM_sel,dT2_drld_TRM_sel,dT2_dTa_TRM_sel,dT2_dqa_TRM_sel,dT2_dalpha_TRM_sel,dT2_demis_TRM_sel,dT2_dra_TRM_sel,dT2_drs_TRM_sel,dT2_dGrnd_TRM_sel,dT2_dra_prime_TRM_sel,...
          Diff_q2, ...
          dq2_dswd_TRM_ref,dq2_drld_TRM_ref,dq2_dTa_TRM_ref,dq2_dqa_TRM_ref,dq2_dalpha_TRM_ref,dq2_demis_TRM_ref,dq2_dra_TRM_ref,dq2_drs_TRM_ref,dq2_dGrnd_TRM_ref,dq2_dra_prime_TRM_ref,...
          dq2_dswd_TRM_sel,dq2_drld_TRM_sel,dq2_dTa_TRM_sel,dq2_dqa_TRM_sel,dq2_dalpha_TRM_sel,dq2_demis_TRM_sel,dq2_dra_TRM_sel,dq2_drs_TRM_sel,dq2_dGrnd_TRM_sel,dq2_dra_prime_TRM_sel] ...
          =REF_Q_TRM(rho_air,Cp,sb,lv,...
              Psurf_ref,swd_ref,lwd_ref,Ta_ref,qa_ref,alpha_ref,emis_ref,Qh_ref,Qle_ref,Ts_ref,T2_ref,q2_ref,...
              Psurf_sel,swd_sel,lwd_sel,Ta_sel,qa_sel,alpha_sel,emis_sel,Qh_sel,Qle_sel,Ts_sel,T2_sel,q2_sel);



dWGT_dalpha_TRM_ref = dWGT_dT2_ref.*dT2_dalpha_TRM_ref+dWGT_dq2_ref.*dq2_dalpha_TRM_ref;
dWGT_dra_TRM_ref    = dWGT_dT2_ref.*dT2_dra_TRM_ref+dWGT_dq2_ref.*dq2_dra_TRM_ref;
dWGT_drs_TRM_ref    = dWGT_dT2_ref.*dT2_drs_TRM_ref+dWGT_dq2_ref.*dq2_drs_TRM_ref;
dWGT_dGrnd_TRM_ref  = dWGT_dT2_ref.*dT2_dGrnd_TRM_ref+dWGT_dq2_ref.*dq2_dGrnd_TRM_ref;
dWGT_dswd_TRM_ref   = dWGT_dT2_ref.*dT2_dswd_TRM_ref + dWGT_dq2_ref.*dq2_dswd_TRM_ref;
dWGT_drld_TRM_ref   = dWGT_dT2_ref.*dT2_drld_TRM_ref + dWGT_dq2_ref.*dq2_drld_TRM_ref;
dWGT_dTa_TRM_ref    = dWGT_dT2_ref.*dT2_dTa_TRM_ref + dWGT_dq2_ref.*dq2_dTa_TRM_ref;
dWGT_dqa_TRM_ref    = dWGT_dT2_ref.*dT2_dqa_TRM_ref + dWGT_dq2_ref.*dq2_dqa_TRM_ref;
dWGT_demis_TRM_ref  = dWGT_dT2_ref.*dT2_demis_TRM_ref + dWGT_dq2_ref.*dq2_demis_TRM_ref;
dWGT_dra_prime_TRM_ref  = dWGT_dT2_ref.*dT2_dra_prime_TRM_ref + dWGT_dq2_ref.*dq2_dra_prime_TRM_ref;


dWGT_dalpha_TRM_sel = dWGT_dT2_sel.*dT2_dalpha_TRM_sel+dWGT_dq2_sel.*dq2_dalpha_TRM_sel;
dWGT_dra_TRM_sel    = dWGT_dT2_sel.*dT2_dra_TRM_sel+dWGT_dq2_sel.*dq2_dra_TRM_sel;
dWGT_drs_TRM_sel    = dWGT_dT2_sel.*dT2_drs_TRM_sel+dWGT_dq2_sel.*dq2_drs_TRM_sel;
dWGT_dGrnd_TRM_sel  = dWGT_dT2_sel.*dT2_dGrnd_TRM_sel+dWGT_dq2_sel.*dq2_dGrnd_TRM_sel;
dWGT_dswd_TRM_sel   = dWGT_dT2_sel.*dT2_dswd_TRM_sel + dWGT_dq2_sel.*dq2_dswd_TRM_sel;
dWGT_drld_TRM_sel   = dWGT_dT2_sel.*dT2_drld_TRM_sel + dWGT_dq2_sel.*dq2_drld_TRM_sel;
dWGT_dTa_TRM_sel    = dWGT_dT2_sel.*dT2_dTa_TRM_sel + dWGT_dq2_sel.*dq2_dTa_TRM_sel;
dWGT_dqa_TRM_sel    = dWGT_dT2_sel.*dT2_dqa_TRM_sel + dWGT_dq2_sel.*dq2_dqa_TRM_sel;
dWGT_demis_TRM_sel  = dWGT_dT2_sel.*dT2_demis_TRM_sel + dWGT_dq2_sel.*dq2_demis_TRM_sel;
dWGT_dra_prime_TRM_sel  = dWGT_dT2_sel.*dT2_dra_prime_TRM_sel + dWGT_dq2_sel.*dq2_dra_prime_TRM_sel;

